version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_DATABASE: test
      #MONGO_INITDB_ROOT_USERNAME: admin
      #MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - fastapi-mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      #ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_URL: mongodb://db:27017/
    networks:
      - fastapi-mongodb
    
  fastapi-dev:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/code
    depends_on:
      - mongodb
    restart: always
    environment:
      - WATCHFILES_FORCE_POLLING=true
    
    env_file:
      - ./server/.env
    networks:
      - fastapi-mongodb
  
  react-dev:
     build:
       context: ./client
       dockerfile: Dockerfile
     ports:
       - 3000:3000
     environment:
       - CHOKIDAR_USEPOLLING=true

  
volumes:
  db:
    driver: local


networks:
  fastapi-mongodb:
    driver: bridge